# Generated by Django 3.2.4 on 2021-07-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='../static/default_user.png', null=True, upload_to='users'),
        ),
    ]
